[[pages]]
path = "/"
screenshotTimestamp = "2026-03-15T10:22:23Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/551aa8d8-0072-47ee-b1c3-15af6e3e7481/8ec7040b-fe17-43f1-a0ca-ef3ec91f0a8e/9EXWSAd"

[[pages]]
path = "/admin/login"
screenshotTimestamp = "2026-03-15T10:22:30Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/551aa8d8-0072-47ee-b1c3-15af6e3e7481/8ec7040b-fe17-43f1-a0ca-ef3ec91f0a8e/yjfWU2w"

[[pages]]
path = "/checkout/1"
screenshotTimestamp = "2026-03-15T10:24:12Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/551aa8d8-0072-47ee-b1c3-15af6e3e7481/8ec7040b-fe17-43f1-a0ca-ef3ec91f0a8e/llhCTjl"
